# Site settings
title: Presentación
description: ¡Bienvenidos! Esta página web contiene mi formación académica y profesional. Asimismo, también contiene mi blog.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "fabriziosulcar.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: FabrizioSulcaR
user_description: ¡Hola! Estudio Economía en la Universidad del Pacífico. Entre mis intereses están la automatización de procesos, las políticas públicas, la ciencia de datos y la economía aplicada. Mi misión es impactar positivamente en las personas y en la sociedad. Cuando no estoy estudiando, estoy escribiendo código.
user_title: Estudiante de Economía
email: fr.sulcar@alum.up.edu.pe
twitter_username: FabrizioSulcaR
github_username:  FabrizioSulcaR
gplus_username:  FabrizioSulcaR

# Google-analytics
google-analytics:
  id: "G-SWQH992CKV"

exclude: ['package.json', 'src' , 'node_modules']
